# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(default='PBLE-novice', max_length=32),
        ),
    ]
