# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 13, 11, 25, 31, 943839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='headline',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='lead',
            field=models.CharField(max_length=64),
        ),
    ]
