# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0002_externallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
