# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0002_auto_20170815_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ManyToManyField(blank=True, to='pblexchange.Course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pblexchange.Tag'),
        ),
    ]
