# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0003_auto_20180429_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 13, 12, 5, 37, 191332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='lead',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
