# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 11:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0003_auto_20180410_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='url',
            field=models.URLField(unique=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
