# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0004_auto_20180429_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 13, 14, 18, 30, 597202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='lead',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
