# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0004_auto_20180411_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
