# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0005_auto_20180412_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=32)),
                ('lead', models.CharField(max_length=64)),
                ('body', models.CharField(max_length=512)),
            ],
        ),
    ]
