# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0007_auto_20180428_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 7, 41, 0, 131416, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 7, 41, 13, 715231, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
