# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 07:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0008_auto_20180428_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 12, 7, 43, 25, 628136)),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 7, 43, 25, 628104)),
        ),
    ]
