# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0010_auto_20180428_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
