# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0011_auto_20180428_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 12, 7, 50, 41, 906553, tzinfo=utc)),
        ),
    ]
