# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 08:23
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import pblexchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0012_auto_20180430_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='end_date',
            field=models.DateField(default=pblexchange.models.delta_now, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='headline',
            field=models.CharField(max_length=32, verbose_name='headline'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='lead',
            field=models.CharField(blank=True, max_length=256, verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
    ]
