# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pblexchange', '0013_auto_20180501_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='headline',
            field=models.CharField(max_length=128, verbose_name='headline'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='lead',
            field=models.CharField(blank=True, max_length=512, verbose_name='lead'),
        ),
    ]
