# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='votes',
            new_name='up_votes',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='votes',
            new_name='up_votes',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='votes',
            new_name='up_votes',
        ),
        migrations.AddField(
            model_name='answer',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
    ]
