# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_answervote_commentvote_questionvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answervote',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionvote',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
