# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_answer_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='up_votes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='up_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='up_votes',
        ),
    ]
