# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pble_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='digest_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='comment_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
