# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pble_subscriptions', '0002_auto_20180410_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='digest_notifications',
        ),
    ]
