# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pble_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en-gb', 'English'), ('da', 'Danish')], default='en-us', max_length=4, verbose_name='language'),
        ),
    ]
