# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pble_users', '0002_userprofile_challenge_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
