# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pble_users', '0002_usersettings_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(default='PBL-novice', max_length=32),
        ),
    ]
