# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pble_users', '0003_auto_20180501_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='language',
            field=models.CharField(choices=[('en-gb', 'English'), ('da', 'Danish')], default='en-gb', max_length=4, verbose_name='language'),
        ),
    ]
