# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pble_users', '0003_auto_20180428_0717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='UserSetting',
        ),
    ]
