# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pble_users', '0006_auto_20180501_1607'),
        ('pble_users', '0003_auto_20180501_1446'),
    ]

    operations = [
    ]
