# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersettings'),
        ('subscriptions', '0002_auto_20180324_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='peers',
            field=models.ManyToManyField(to='users.UserProfile'),
        ),
    ]
