# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pble_questions', '0003_featuredcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
