# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pble_questions', '0004_auto_20180430_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredcategory',
            options={'verbose_name_plural': 'featured categories'},
        ),
    ]
