# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pble_questions', '0006_auto_20180430_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredcategory',
            old_name='text_dk',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='featuredcategory',
            name='text_en',
        ),
    ]
