# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pble_questions', '0008_auto_20180430_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='bounty',
            field=models.PositiveIntegerField(default=0, verbose_name='bounty'),
        ),
    ]
