# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pble_questions', '0009_auto_20180501_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='da_description',
        ),
        migrations.RenameField(
            model_name='featuredcategory',
            old_name='dk_text',
            new_name='da_text',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='en_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='en_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=160),
            preserve_default=False,
        ),
    ]
