# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pble_questions', '0012_auto_20180501_1610'),
        ('pble_questions', '0009_auto_20180501_1446'),
    ]

    operations = [
    ]
